name: Deploy to Mirohost
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: vs2877.mirohost.net
          username: citolabk
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /var/www/citolabk/citolabk.pharmasco.com/
