name: Test FTP Secret
on:
  workflow_dispatch:   # запуск вручну

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show secret length
        run: |
          echo "Secret length: ${#FTP_PASSWORD}"
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

      - name: Masked echo
        run: |
          echo "Secret value is: $FTP_PASSWORD"
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
